### ISSUE TITLE
```panic!``` during playground example runtime

### ISSUE THREAD

**Issue by lesavonfou** [murtyjones/purdy#28]
Hi,

I am trying to run your example but I am facing a parsing error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Found leftover content in stream', examples\playground\src\main.rs:137:72
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I believe the error comes from:

```
impl<'a> Stream<'a> {
    pub fn get_content(&self) -> Result<Vec<StreamObject<'a>>> {
        let (rest, content) = stream_objects(self.content)?;
        if !rest.is_empty() {
            return Err(ParseError::FailedToParseAllStreamContent.into());
        }
        Ok(content)
    }
}
```

Where an object read from ```sample-no-xref-entries.pdf``` is not fully parsed.
Commenting out ```!rest.is_empty()``` still generates an image.

**Comment by murtyjones** [comment]
Hi @lesavonfou!

Sorry about that -- now that purdy is public I need to transition to using pull requests so that I don't commit work half-done.

In this case I added some data to `pdfs/sample-no-xref-entries/sample-no-xref-entries.pdf` and committed it before I had added the matching parse logic. So in that sense, the code snippet you linked was doing its job by letting me know that there was content in `sample-no-xref-entries.pdf` not being parsed.

---

Anyways, I added that parsing logic yesterday in fc96d37 so I think you might just need to get the latest from master. Let me know if you still have issues running `make eg1` after that

**Comment by lesavonfou** [comment]
Thanks for the feedback.

I am currently using the latest version, and it is still failing  (b044f093d424456f5c9f09ca476abb01974e9b58).
I will try to look more in detail tomorrow 😄

**Comment by murtyjones** [comment]
How strange...

I can't reproduce but I added some more detail to the error. When you have a chance can you re-run and share the new output? Should look like:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Found leftover content in stream. leftover content: (foobar
)', examples/playground/src/main.rs:137:72
```

I see backslashes in your error message above so guessing you have a windows machine. Could be an issue with byte parsing, although I'm not sure what off the top of my head.

**Comment by lesavonfou** [comment]
I am not sure it's linked to the OS path different because I can see that the file chunk is read.
May something is wrong with the PDF object parsing rules?
 
Here is the error after pull the latest commit:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Found leftover content in stream. leftover content: (���-�♦��5)�☺�e3)�☺
% Zero-area square
10 w
2 J
65 15 m
65 15 l
S
2 w
[0 5] 0 d
85 15 m
105 30 l
115 17 l
s
)', examples\playground\src\main.rs:137:72
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\playground.exe` (exit code: 101)
```

**Comment by murtyjones** [comment]
Yeah it's certainly a parsing issue. The OS path was useful in identifying your system because it most likely is an issue with the file having different contents on a windows machine.

I don't have a windows machine but I'll see if I can reproduce your issue using github actions

**Comment by murtyjones** [comment]
@lesavonfou if you run the test suite using `cargo test --all --verbose` do you get any errors?

**Comment by lesavonfou** [comment]
tests are all passing on Windows and Linux.

I fiddle a bit with the `sample-no-xref-entries.pdf` and I noticed that the parsing fails only on this section of the object 11 stream:
```
% Zero-area circle
0 0 1 SC
10 w 1 J
45 15 m
45 15 l
S
1 0.2 1 SC
% Zero-area square
10 w
2 J
65 15 m
65 15 l
S
2 w
[0 5] 0 d 
85 15 m
105 30 l
115 17 l
s
```

I also tried to use `pdf-rs` library to read this pdf file but it was crashing as well.

**Comment by murtyjones** [comment]
Yeah, for some reason on your machine the document has non-ascii characters for that object:

```
 (���-�♦��5)�☺�e3)�☺
% Zero-area square
10 w
2 J
65 15 m
```

but on my machine it's all ascii:

```
1 0.2 1 SC
% Zero-area square
10 w
2 J
```

not sure where the junk is coming from

**Comment by murtyjones** [comment]
@lesavonfou I added a test that might reproduce this error the next time you run the test suite.

Unfortunately it doesn't reproduce in CI on windows, so I might need more details about your machine and your version of Rust.

**Comment by lesavonfou** [comment]
Thanks for the effort. I noticed that this bug occurs most of the time but _**not**_ all the time.
I could then compare the flow between a succesfull run and a failing one. From that, I can feel something goes wrong in the `stream_object` parser.

```
[crates\pdf\src\stream\parsers.rs:183] String::from_utf8_lossy(&input.clone()) = "/DeviceRGB CS\r\n% Zero-length, zero-area line\r\n0.3 1 1 sc\r\n10 10 m\r\n10 10 l\r\nf\r\n% Set non-stroke color to red\r\n1 0 0 sc\r\n% Zero-area line\r\n20 10 m\r\n20 20 l\r\nf\r\n% Zero-width rect\r\n0 1 0 sc\r\n30 10 0 10 re\r\nf\r\n% Zero-area circle\r\n0 0 1 SC\r\n10 w 1 J\r\n45 15 m\r\n45 15 l\r\nS\r\n1 0.2 1 SC\r\n% Zero-area square\r\n10 w\r\n2 J\r\n65 15 m\r\n65 15 l\r\nS\r\n2 w\r\n[0 5] 0 d \r\n85 15 m\r\n105 30 l\r\n115 17 l\r\ns\r\n"
[crates\pdf\src\stream\parsers.rs:183] String::from_utf8_lossy(&input.clone()) = "0.3 1 1 sc\r\n10 10 m\r\n10 10 l\r\nf\r\n% Set non-stroke color to red\r\n1 0 0 sc\r\n% Zero-area line\r\n20 10 m\r\n20 20 l\r\nf\r\n% Zero-width rect\r\n0 1 0 sc\r\n30 10 0 10 re\r\nf\r\n% Zero-area circle\r\n0 0 1 SC\r\n10 w 1 J\r\n45 15 m\r\n45 15 l\r\nS\r\n1 0.2 1 SC\r\n% Zero-area square\r\n10 w\r\n2 J\r\n65 15 m\r\n65 15 l\r\nS\r\n2 w\r\n[0 5] 0 d \r\n85 15 m\r\n105 30 l\r\n115 17 l\r\ns\r\n"
[crates\pdf\src\stream\parsers.rs:183] String::from_utf8_lossy(&input.clone()) = "10 10 l\r\nf\r\n% Set non-stroke color to red\r\n1 0 0 sc\r\n% Zero-area line\r\n20 10 m\r\n20 20 l\r\nf\r\n% Zero-width rect\r\n0 1 0 sc\r\n30 10 0 10 re\r\nf\r\n% Zero-area circle\r\n0 0 1 SC\r\n10 w 1 J\r\n45 15 m\r\n45 15 l\r\nS\r\n1 0.2 1 SC\r\n% Zero-area square\r\n10 w\r\n2 J\r\n65 15 m\r\n65 15 l\r\nS\r\n2 w\r\n[0 5] 0 d \r\n85 15 m\r\n105 30 l\r\n115 17 l\r\ns\r\n"
[crates\pdf\src\stream\parsers.rs:183] String::from_utf8_lossy(&input.clone()) = "f\r\n% Set non-stroke color to red\r\n1 0 0 sc\r\n% Zero-area line\r\n20 10 m\r\n20 20 l\r\nf\r\n% Zero-width rect\r\n0 1 0 sc\r\n30 10 0 10 re\r\nf\r\n% Zero-area circle\r\n0 0 1 SC\r\n10 w 1 J\r\n45 15 m\r\n45 15 l\r\nS\r\n1 0.2 1 SC\r\n% Zero-area square\r\n10 w\r\n2 J\r\n65 15 m\r\n65 15 l\r\nS\r\n2 w\r\n[0 5] 0 d \r\n85 15 m\r\n105 30 l\r\n115 17 l\r\ns\r\n"
[crates\pdf\src\stream\parsers.rs:183] String::from_utf8_lossy(&input.clone()) = "1 0 0 sc\r\n% Zero-area line\r\n20 10 m\r\n20 20 l\r\nf\r\n% Zero-width rect\r\n0 1 0 sc\r\n30 10 0 10 re\r\nf\r\n% Zero-area circle\r\n0 0 1 SC\r\n10 w 1 J\r\n45 15 m\r\n45 15 l\r\nS\r\n1 0.2 1 SC\r\n% Zero-area square\r\n10 w\r\n2 J\r\n65 15 m\r\n65 15 l\r\nS\r\n2 w\r\n[0 5] 0 d \r\n85 15 m\r\n105 30 l\r\n115 17 l\r\ns\r\n"
[crates\pdf\src\stream\parsers.rs:183] String::from_utf8_lossy(&input.clone()) = "20 20 l\r\nf\r\n% Zero-width rect\r\n0 1 0 sc\r\n30 10 0 10 re\r\nf\r\n% Zero-area circle\r\n0 0 1 SC\r\n10 w 1 J\r\n45 15 m\r\n45 15 l\r\nS\r\n1 0.2 1 SC\r\n% Zero-area square\r\n10 w\r\n2 J\r\n65 15 m\r\n65 15 l\r\nS\r\n2 w\r\n[0 5] 0 d \r\n85 15 m\r\n105 30 l\r\n115 17 l\r\ns\r\n"
[crates\pdf\src\stream\parsers.rs:183] String::from_utf8_lossy(&input.clone()) = "f\r\n% Zero-width rect\r\n0 1 0 sc\r\n30 10 0 10 re\r\nf\r\n% Zero-area circle\r\n0 0 1 SC\r\n10 w 1 J\r\n45 15 m\r\n45 15 l\r\nS\r\n1 0.2 1 SC\r\n% Zero-area square\r\n10 w\r\n2 J\r\n65 15 m\r\n65 15 l\r\nS\r\n2 w\r\n[0 5] 0 d \r\n85 15 m\r\n105 30 l\r\n115 17 l\r\ns\r\n"
[crates\pdf\src\stream\parsers.rs:183] String::from_utf8_lossy(&input.clone()) = "0 1 0 sc\r\n30 10 0 10 re\r\nf\r\n% Zero-area circle\r\n0 0 1 SC\r\n10 w 1 J\r\n45 15 m;)�#�Z\u{0}\u{0}p���3\u{2}\u{0}\u{0}�e��3\u{2}\u{0}\u{0}\r\n% Zero-area square\r\n10 w\r\n2 J\r\n65 15 m\r\n65 15 l\r\nS\r\n2 w\r\n[0 5] 0 d \r\n85 15 m\r\n105 30 l\r\n115 17 l\r\ns\r\n"
[crates\pdf\src\stream\parsers.rs:183] String::from_utf8_lossy(&input.clone()) = "30 10 0 10 re\r\nf\r\n% Zero-area circle\r\n0 0 1 SC\r\n10 w 1 J\r\n45 15 m9)� �Z\u{0}\u{0}pthread 'main' panicked at 'failed printing to stderr: Windows stdio in console mode does not support writing non-UTF-8 byte sequences', library\std\src\io\stdio.rs:1187:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

After several runs I can see that the garbage is inserted always at the moment: after the parsing of the comment `% Zero-width rect\r\n`. 

I have a feeling that we are narrowing down the problem here, it may lead to a `nom` bug 😞 .

Regarding your question over my rustc:

```
installed toolchains
--------------------

stable-x86_64-pc-windows-msvc
nightly-x86_64-pc-windows-msvc (default)

installed targets for active toolchain
--------------------------------------

x86_64-pc-windows-msvc
x86_64-unknown-linux-musl

active toolchain
----------------

nightly-x86_64-pc-windows-msvc (default)
rustc 1.60.0-nightly (ec4bcaac4 2022-01-15)
```

**Comment by murtyjones** [comment]
> Thanks for the effort. I noticed that this bug occurs most of the time but not all the time.

How incredibly odd.

It's almost like
